apiVersion: batch/v1
kind: CronJob
metadata:
  name: kh-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hk-pods
            image: busybox
            args:
              - /bin/sh
              - -c
              - date; echo Hello from the kube cluster
          restartPolicy: OnFailure
