# Question 4: Arguments

# Create a pod named kplabs-logging

# The Pod should have a container running from the nginx image with the following arguments:

#     - /bin/sh
#     - -c
#     - >
#       i=0;
#       while true;
#       do
#         echo "$i: $(date)" >> /var/log/1.log;
#         echo "$(date) INFO $i" >> /var/log/2.log;
#         i=$((i+1));
#         sleep 1;
#       done

# Once POD is created, connect to the POD and verify the contents of /var/log/1.log and /var/log/2.log
apiVersion: v1
kind: Pod
metadata:
  name: kplabs-logging
spec:
  containers:
    - name: kplabs-logging
      image: nginx
      args:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do
            echo "$i: $(date)" >> /var/log/1.log;
            echo "$(date) INFO $i" >> /var/log/2.log;
            i=$((i+1));
            sleep 1;
          done