# Question 6:  CronJob

# Create a job named kplabs-cron.
# The job should run every minute and should run following command "curl kplabs.in/ping".
# Terminate the container within 10 seconds if it does not run.


apiVersion: batch/v1
kind: CronJob
metadata:
  name: kplabs-cron
spec:
  jobTemplate:
    metadata:
      name: kplabs-cron
    spec:
      activeDeadlineSeconds: 10
      template:
        spec:
          containers:
          - image: busybox
            name: kplabs-cron
            args:
              - /bin/sh
              - "-c"
              - curl google.com
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
